Move UUID package to "dependencies."
jccguimaraes/project-viewer-plus pull request #12
Opened 2018-05-29 22:10 UTC by phyllisstein

Hey! This looks neat, I'm glad to see a refactor of `project-viewer`. Unfortunately I had some trouble installing it because the `uuid` package is used in production bits of the code. This moves the package to `dependencies` in `package.json`.

2018-05-29 23:04 UTC, jccguimaraes commented
😱 such a rookie mistake! ahahaha
thanks @phyllisstein 

It is still very green... the bare minimum has been migrated

2018-05-29 23:06 UTC, jccguimaraes commented
i am still missing the commit message validation apparently. could you be so kind and change it to something like `fix: Move UUID package to "dependencies"`?

2018-05-29 23:06 UTC, jccguimaraes requested changes
i am still missing the commit message validation apparently. could you be so kind and change it to something like fix: Move UUID package to "dependencies"?

2018-05-30 14:15 UTC, phyllisstein commented
Hah, it happens! Just pushed up a new commit message, let me know if you need anything else.

2018-05-30 14:58 UTC, jccguimaraes approved these changes

2018-05-30 16:26 UTC, merged